[profile.default]
src = "contracts"
out = "out"
via_ir = true
libs = ["node_modules", "lib"]
remappings = [
    "@chainlink/=node_modules/@chainlink/",
    "@eth-optimism/=node_modules/@eth-optimism/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
localhost = "http://localhost:8545"
ethereum = "https://eth.llamarpc.com"
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"