[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
ffi = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

solc = '0.8.25'
extra_output = ["devdoc", "userdoc", "storagelayout"]
evm_version = 'london'
use_literal_content = true
fs_permissions = [{ access = "read-write", path = "./" }]

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = true

[rpc_endpoints]
ethereum = "https://eth.llamarpc.com"
goerli = "https://ethereum-goerli.publicnode.com"
ronin-mainnet = "https://api-partner.roninchain.com/rpc"
ronin-testnet = "https://saigon-archive.roninchain.com/rpc"
localhost = "http://localhost:8545"

[dependencies]
forge-std = { version = "1.8.2" }
solady = { version = "0.0.206" }
"@openzeppelin-contracts" = { version = "4.9.3" }