[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

fs_permissions = [{ access = "read-write", path = "./" }]


remappings = [
  '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/'
]
[dependencies]
"@openzeppelin-v4" = { version = "4.8.2", url = "https://github.com/OpenZeppelin/openzeppelin-contracts/archive/refs/tags/v4.8.2.zip" }


[etherscan]
avalanche-fuji = { key = "${ETHERSCAN_API_KEY}", chain = 43113, url = "https://api-testnet.snowtrace.io/api" }
arbitrum-sepolia = { key = "${ARBISCAN_API_KEY}", chain = 421613, url = "https://api-sepolia.arbiscan.io/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111, url = "https://api-sepolia.etherscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
localhost = "http://localhost:8545"
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
ronin-testnet = "https://saigon-archive.roninchain.com/rpc"